onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group hwpe_cfg_slave /tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/hwpe_cfg_slave/ID_WIDTH
add wave -noupdate -group hwpe_cfg_slave /tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/hwpe_cfg_slave/req
add wave -noupdate -group hwpe_cfg_slave /tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/hwpe_cfg_slave/add
add wave -noupdate -group hwpe_cfg_slave /tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/hwpe_cfg_slave/wen
add wave -noupdate -group hwpe_cfg_slave /tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/hwpe_cfg_slave/wdata
add wave -noupdate -group hwpe_cfg_slave /tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/hwpe_cfg_slave/be
add wave -noupdate -group hwpe_cfg_slave /tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/hwpe_cfg_slave/gnt
add wave -noupdate -group hwpe_cfg_slave /tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/hwpe_cfg_slave/id
add wave -noupdate -group hwpe_cfg_slave /tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/hwpe_cfg_slave/r_valid
add wave -noupdate -group hwpe_cfg_slave /tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/hwpe_cfg_slave/r_opc
add wave -noupdate -group hwpe_cfg_slave /tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/hwpe_cfg_slave/r_id
add wave -noupdate -group hwpe_cfg_slave /tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/hwpe_cfg_slave/r_rdata
add wave -noupdate -group {i_fft[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/i_fft/DATA_WIDTH}
add wave -noupdate -group {i_fft[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/i_fft/clk}
add wave -noupdate -group {i_fft[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/i_fft/rst_n}
add wave -noupdate -group {i_fft[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/i_fft/valid_in}
add wave -noupdate -group {i_fft[0]} -radix binary {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/i_fft/in_r}
add wave -noupdate -group {i_fft[0]} -radix binary {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/i_fft/in_i}
add wave -noupdate -group {i_fft[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/i_fft/out_r}
add wave -noupdate -group {i_fft[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/i_fft/out_i}
add wave -noupdate -group {i_fft[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/i_fft/valid_out}
add wave -noupdate -group {i_fft[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/i_fft/frame_done}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/BW_ALIGNED}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/DATA_WIDTH}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/clk_i}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/rst_ni}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/test_mode_i}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/ctrl_i}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/flags_o}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_data_i}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/sample_data_in}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_data_o}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/sample_data_out}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/in32}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/out32}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/empty_data_in}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/full_data_in}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/pop_data_in}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/empty_data_out}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/full_data_out}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/push_data_out}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/valid_in}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/valid_out}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/valid_in_start}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/valid_in_finish}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/count_to_pop_data_in}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/count_to_disable_valid}
add wave -noupdate -group i_engine {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/count_to_push_data_out}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/FALL_THROUGH}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/DATA_WIDTH}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/DEPTH}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/ADDR_DEPTH}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/FifoDepth}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/clk_i}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/rst_ni}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/flush_i}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/testmode_i}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/full_o}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/empty_o}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/usage_o}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/data_i}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/push_i}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/data_o}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/pop_i}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/gate_clock}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/read_pointer_n}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/read_pointer_q}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/write_pointer_n}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/write_pointer_q}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/status_cnt_n}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/status_cnt_q}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/mem_n}
add wave -noupdate -group fifo_pre_data_in {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_pre_data_in/mem_q}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/FALL_THROUGH}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/DATA_WIDTH}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/DEPTH}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/ADDR_DEPTH}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/FifoDepth}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/clk_i}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/rst_ni}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/flush_i}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/testmode_i}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/full_o}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/empty_o}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/usage_o}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/data_i}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/push_i}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/data_o}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/pop_i}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/gate_clock}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/read_pointer_n}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/read_pointer_q}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/write_pointer_n}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/write_pointer_q}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/status_cnt_n}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/status_cnt_q}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/mem_n}
add wave -noupdate -group fifo_post_data_out {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[0]/i_fft/i_engine/fifo_post_data_out/mem_q}
add wave -noupdate -group {i_fft[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[1]/i_fft/i_engine/i_fft/clk}
add wave -noupdate -group {i_fft[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[1]/i_fft/i_engine/i_fft/rst_n}
add wave -noupdate -group {i_fft[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[1]/i_fft/i_engine/i_fft/valid_in}
add wave -noupdate -group {i_fft[1]} -radix binary {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[1]/i_fft/i_engine/i_fft/in_r}
add wave -noupdate -group {i_fft[1]} -radix binary {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[1]/i_fft/i_engine/i_fft/in_i}
add wave -noupdate -group {i_fft[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[1]/i_fft/i_engine/i_fft/out_r}
add wave -noupdate -group {i_fft[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[1]/i_fft/i_engine/i_fft/out_i}
add wave -noupdate -group {i_fft[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[1]/i_fft/i_engine/i_fft/valid_out}
add wave -noupdate -group {i_fft[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[1]/i_fft/i_engine/i_fft/frame_done}
add wave -noupdate -group {i_fft[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[2]/i_fft/i_engine/i_fft/clk}
add wave -noupdate -group {i_fft[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[2]/i_fft/i_engine/i_fft/rst_n}
add wave -noupdate -group {i_fft[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[2]/i_fft/i_engine/i_fft/valid_in}
add wave -noupdate -group {i_fft[2]} -radix binary {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[2]/i_fft/i_engine/i_fft/in_r}
add wave -noupdate -group {i_fft[2]} -radix binary {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[2]/i_fft/i_engine/i_fft/in_i}
add wave -noupdate -group {i_fft[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[2]/i_fft/i_engine/i_fft/out_r}
add wave -noupdate -group {i_fft[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[2]/i_fft/i_engine/i_fft/out_i}
add wave -noupdate -group {i_fft[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[2]/i_fft/i_engine/i_fft/valid_out}
add wave -noupdate -group {i_fft[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[2]/i_fft/i_engine/i_fft/frame_done}
add wave -noupdate -group {i_fft[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[3]/i_fft/i_engine/i_fft/clk}
add wave -noupdate -group {i_fft[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[3]/i_fft/i_engine/i_fft/rst_n}
add wave -noupdate -group {i_fft[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[3]/i_fft/i_engine/i_fft/valid_in}
add wave -noupdate -group {i_fft[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[3]/i_fft/i_engine/i_fft/in_r}
add wave -noupdate -group {i_fft[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[3]/i_fft/i_engine/i_fft/in_i}
add wave -noupdate -group {i_fft[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[3]/i_fft/i_engine/i_fft/out_r}
add wave -noupdate -group {i_fft[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[3]/i_fft/i_engine/i_fft/out_i}
add wave -noupdate -group {i_fft[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[3]/i_fft/i_engine/i_fft/valid_out}
add wave -noupdate -group {i_fft[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[3]/i_fft/i_engine/i_fft/frame_done}
add wave -noupdate -group {i_fft[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[4]/i_fft/i_engine/i_fft/clk}
add wave -noupdate -group {i_fft[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[4]/i_fft/i_engine/i_fft/rst_n}
add wave -noupdate -group {i_fft[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[4]/i_fft/i_engine/i_fft/valid_in}
add wave -noupdate -group {i_fft[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[4]/i_fft/i_engine/i_fft/in_r}
add wave -noupdate -group {i_fft[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[4]/i_fft/i_engine/i_fft/in_i}
add wave -noupdate -group {i_fft[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[4]/i_fft/i_engine/i_fft/out_r}
add wave -noupdate -group {i_fft[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[4]/i_fft/i_engine/i_fft/out_i}
add wave -noupdate -group {i_fft[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[4]/i_fft/i_engine/i_fft/valid_out}
add wave -noupdate -group {i_fft[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[4]/i_fft/i_engine/i_fft/frame_done}
add wave -noupdate -group {i_fft[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[5]/i_fft/i_engine/i_fft/clk}
add wave -noupdate -group {i_fft[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[5]/i_fft/i_engine/i_fft/rst_n}
add wave -noupdate -group {i_fft[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[5]/i_fft/i_engine/i_fft/valid_in}
add wave -noupdate -group {i_fft[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[5]/i_fft/i_engine/i_fft/in_r}
add wave -noupdate -group {i_fft[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[5]/i_fft/i_engine/i_fft/in_i}
add wave -noupdate -group {i_fft[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[5]/i_fft/i_engine/i_fft/out_r}
add wave -noupdate -group {i_fft[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[5]/i_fft/i_engine/i_fft/out_i}
add wave -noupdate -group {i_fft[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[5]/i_fft/i_engine/i_fft/valid_out}
add wave -noupdate -group {i_fft[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[5]/i_fft/i_engine/i_fft/frame_done}
add wave -noupdate -group {i_fft[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[6]/i_fft/i_engine/i_fft/clk}
add wave -noupdate -group {i_fft[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[6]/i_fft/i_engine/i_fft/rst_n}
add wave -noupdate -group {i_fft[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[6]/i_fft/i_engine/i_fft/valid_in}
add wave -noupdate -group {i_fft[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[6]/i_fft/i_engine/i_fft/in_r}
add wave -noupdate -group {i_fft[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[6]/i_fft/i_engine/i_fft/in_i}
add wave -noupdate -group {i_fft[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[6]/i_fft/i_engine/i_fft/out_r}
add wave -noupdate -group {i_fft[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[6]/i_fft/i_engine/i_fft/out_i}
add wave -noupdate -group {i_fft[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[6]/i_fft/i_engine/i_fft/valid_out}
add wave -noupdate -group {i_fft[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[6]/i_fft/i_engine/i_fft/frame_done}
add wave -noupdate -group {i_fft[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/i_fft/clk}
add wave -noupdate -group {i_fft[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/i_fft/rst_n}
add wave -noupdate -group {i_fft[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/i_fft/valid_in}
add wave -noupdate -group {i_fft[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/i_fft/in_r}
add wave -noupdate -group {i_fft[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/i_fft/in_i}
add wave -noupdate -group {i_fft[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/i_fft/out_r}
add wave -noupdate -group {i_fft[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/i_fft/out_i}
add wave -noupdate -group {i_fft[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/i_fft/valid_out}
add wave -noupdate -group {i_fft[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/i_fft/frame_done}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/BW_ALIGNED}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/DATA_WIDTH}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/clk_i}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/rst_ni}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/test_mode_i}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/ctrl_i}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/flags_o}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_data_i}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/sample_data_in}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_data_o}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/sample_data_out}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/in32}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/out32}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/empty_data_in}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/full_data_in}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/pop_data_in}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/empty_data_out}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/full_data_out}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/push_data_out}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/valid_in}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/valid_out}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/valid_in_start}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/valid_in_finish}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/count_to_pop_data_in}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/count_to_disable_valid}
add wave -noupdate -group {i_engine[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/count_to_push_data_out}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/FALL_THROUGH}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/DATA_WIDTH}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/DEPTH}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/ADDR_DEPTH}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/FifoDepth}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/clk_i}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/rst_ni}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/flush_i}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/testmode_i}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/full_o}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/empty_o}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/usage_o}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/data_i}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/push_i}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/data_o}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/pop_i}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/gate_clock}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/read_pointer_n}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/read_pointer_q}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/write_pointer_n}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/write_pointer_q}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/status_cnt_n}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/status_cnt_q}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/mem_n}
add wave -noupdate -group {fifo_pre_data_in[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_pre_data_in/mem_q}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/FALL_THROUGH}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/DATA_WIDTH}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/DEPTH}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/ADDR_DEPTH}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/FifoDepth}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/clk_i}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/rst_ni}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/flush_i}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/testmode_i}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/full_o}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/empty_o}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/usage_o}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/data_i}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/push_i}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/data_o}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/pop_i}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/gate_clock}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/read_pointer_n}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/read_pointer_q}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/write_pointer_n}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/write_pointer_q}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/status_cnt_n}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/status_cnt_q}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/mem_n}
add wave -noupdate -group {fifo_post_data_out[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/hwpe_gen/hwpe_subsystem_i/FFT_gen[7]/i_fft/i_engine/fifo_post_data_out/mem_q}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/NumWords}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/DataWidth}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/ByteWidth}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/NumPorts}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/Latency}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/SimInit}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/PrintSimCfg}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/ImplKey}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/AddrWidth}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/BeWidth}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/clk_i}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/rst_ni}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/req_i}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/we_i}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/addr_i}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/wdata_i}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/be_i}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/rdata_o}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/sram}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/r_addr_q}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/init_val}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/rdata_q}
add wave -noupdate -group {i_bank[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[0]/i_bank/rdata_d}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/NumWords}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/DataWidth}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/ByteWidth}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/NumPorts}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/Latency}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/SimInit}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/PrintSimCfg}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/ImplKey}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/AddrWidth}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/BeWidth}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/clk_i}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/rst_ni}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/req_i}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/we_i}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/addr_i}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/wdata_i}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/be_i}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/rdata_o}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/sram}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/r_addr_q}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/init_val}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/rdata_q}
add wave -noupdate -group {i_bank[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[1]/i_bank/rdata_d}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/NumWords}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/DataWidth}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/ByteWidth}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/NumPorts}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/Latency}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/SimInit}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/PrintSimCfg}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/ImplKey}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/AddrWidth}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/BeWidth}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/clk_i}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/rst_ni}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/req_i}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/we_i}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/addr_i}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/wdata_i}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/be_i}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/rdata_o}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/sram}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/r_addr_q}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/init_val}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/rdata_q}
add wave -noupdate -group {i_bank[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[2]/i_bank/rdata_d}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/NumWords}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/DataWidth}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/ByteWidth}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/NumPorts}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/Latency}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/SimInit}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/PrintSimCfg}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/ImplKey}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/AddrWidth}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/BeWidth}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/clk_i}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/rst_ni}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/req_i}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/we_i}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/addr_i}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/wdata_i}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/be_i}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/rdata_o}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/sram}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/r_addr_q}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/init_val}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/rdata_q}
add wave -noupdate -group {i_bank[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[3]/i_bank/rdata_d}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/NumWords}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/DataWidth}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/ByteWidth}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/NumPorts}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/Latency}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/SimInit}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/PrintSimCfg}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/ImplKey}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/AddrWidth}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/BeWidth}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/clk_i}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/rst_ni}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/req_i}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/we_i}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/addr_i}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/wdata_i}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/be_i}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/rdata_o}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/sram}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/r_addr_q}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/init_val}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/rdata_q}
add wave -noupdate -group {i_bank[4]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[4]/i_bank/rdata_d}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/NumWords}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/DataWidth}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/ByteWidth}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/NumPorts}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/Latency}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/SimInit}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/PrintSimCfg}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/ImplKey}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/AddrWidth}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/BeWidth}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/clk_i}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/rst_ni}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/req_i}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/we_i}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/addr_i}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/wdata_i}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/be_i}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/rdata_o}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/sram}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/r_addr_q}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/init_val}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/rdata_q}
add wave -noupdate -group {i_bank[5]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[5]/i_bank/rdata_d}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/NumWords}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/DataWidth}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/ByteWidth}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/NumPorts}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/Latency}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/SimInit}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/PrintSimCfg}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/ImplKey}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/AddrWidth}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/BeWidth}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/clk_i}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/rst_ni}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/req_i}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/we_i}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/addr_i}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/wdata_i}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/be_i}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/rdata_o}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/sram}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/r_addr_q}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/init_val}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/rdata_q}
add wave -noupdate -group {i_bank[6]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[6]/i_bank/rdata_d}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/NumWords}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/DataWidth}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/ByteWidth}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/NumPorts}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/Latency}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/SimInit}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/PrintSimCfg}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/ImplKey}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/AddrWidth}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/BeWidth}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/clk_i}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/rst_ni}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/req_i}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/we_i}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/addr_i}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/wdata_i}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/be_i}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/rdata_o}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/sram}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/r_addr_q}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/init_val}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/rdata_q}
add wave -noupdate -group {i_bank[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[7]/i_bank/rdata_d}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/NumWords}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/DataWidth}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/ByteWidth}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/NumPorts}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/Latency}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/SimInit}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/PrintSimCfg}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/ImplKey}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/AddrWidth}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/BeWidth}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/clk_i}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/rst_ni}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/req_i}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/we_i}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/addr_i}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/wdata_i}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/be_i}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/rdata_o}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/sram}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/r_addr_q}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/init_val}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/rdata_q}
add wave -noupdate -group {i_bank[32]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[32]/i_bank/rdata_d}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/NumWords}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/DataWidth}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/ByteWidth}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/NumPorts}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/Latency}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/SimInit}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/PrintSimCfg}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/ImplKey}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/AddrWidth}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/BeWidth}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/clk_i}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/rst_ni}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/req_i}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/we_i}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/addr_i}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/wdata_i}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/be_i}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/rdata_o}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/sram}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/r_addr_q}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/init_val}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/rdata_q}
add wave -noupdate -group {i_bank[63]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/tcdm_banks_i/banks_gen[63]/i_bank/rdata_d}
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/NB_CTRLS
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/NB_CORES
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/NB_OUTSND_BURSTS
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/MCHAN_BURST_LENGTH
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/AXI_ADDR_WIDTH
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/AXI_DATA_WIDTH
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/AXI_USER_WIDTH
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/AXI_ID_WIDTH
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/PE_ID_WIDTH
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/TCDM_ADD_WIDTH
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/DATA_WIDTH
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ADDR_WIDTH
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/BE_WIDTH
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/clk_i
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/rst_ni
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/test_mode_i
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/term_event_cl_o
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/term_irq_cl_o
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/term_event_pe_o
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/term_irq_pe_o
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/term_event_o
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/term_irq_o
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/busy_o
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_ctrl_bus_wdata
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_ctrl_bus_add
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_ctrl_bus_req
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_ctrl_bus_wen
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_ctrl_bus_be
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_ctrl_bus_id
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_ctrl_bus_gnt
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_ctrl_bus_r_rdata
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_ctrl_bus_r_valid
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_ctrl_bus_r_opc
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_ctrl_bus_r_id
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_tcdm_bus_wdata
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_tcdm_bus_add
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_tcdm_bus_req
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_tcdm_bus_wen
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_tcdm_bus_be
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_tcdm_bus_gnt
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_tcdm_bus_r_rdata
add wave -noupdate -group dmac_wrap_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/s_tcdm_bus_r_valid
add wave -noupdate -group {ctrl_slave[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[0]/req}
add wave -noupdate -group {ctrl_slave[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[0]/add}
add wave -noupdate -group {ctrl_slave[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[0]/wen}
add wave -noupdate -group {ctrl_slave[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[0]/wdata}
add wave -noupdate -group {ctrl_slave[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[0]/be}
add wave -noupdate -group {ctrl_slave[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[0]/gnt}
add wave -noupdate -group {ctrl_slave[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[0]/r_opc}
add wave -noupdate -group {ctrl_slave[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[0]/r_rdata}
add wave -noupdate -group {ctrl_slave[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[0]/r_valid}
add wave -noupdate -group {ctrl_slave[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[2]/req}
add wave -noupdate -group {ctrl_slave[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[2]/add}
add wave -noupdate -group {ctrl_slave[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[2]/wen}
add wave -noupdate -group {ctrl_slave[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[2]/wdata}
add wave -noupdate -group {ctrl_slave[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[2]/be}
add wave -noupdate -group {ctrl_slave[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[2]/gnt}
add wave -noupdate -group {ctrl_slave[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[2]/r_opc}
add wave -noupdate -group {ctrl_slave[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[2]/r_rdata}
add wave -noupdate -group {ctrl_slave[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[2]/r_valid}
add wave -noupdate -group {ctrl_slave[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[7]/req}
add wave -noupdate -group {ctrl_slave[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[7]/add}
add wave -noupdate -group {ctrl_slave[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[7]/wen}
add wave -noupdate -group {ctrl_slave[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[7]/wdata}
add wave -noupdate -group {ctrl_slave[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[7]/be}
add wave -noupdate -group {ctrl_slave[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[7]/gnt}
add wave -noupdate -group {ctrl_slave[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[7]/r_opc}
add wave -noupdate -group {ctrl_slave[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[7]/r_rdata}
add wave -noupdate -group {ctrl_slave[7]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/ctrl_slave[7]/r_valid}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/DW}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/AW}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/BW}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/WW}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/OW}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/UW}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/clk}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/req}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/gnt}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/lrdy}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/add}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/wen}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/data}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/be}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/boffs}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/user}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/r_data}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/r_valid}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/r_opc}
add wave -noupdate -group {tcdm_master[0]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[0]/r_user}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/DW}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/AW}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/BW}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/WW}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/OW}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/UW}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/clk}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/req}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/gnt}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/lrdy}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/add}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/wen}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/data}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/be}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/boffs}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/user}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/r_data}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/r_valid}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/r_opc}
add wave -noupdate -group {tcdm_master[1]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[1]/r_user}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/DW}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/AW}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/BW}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/WW}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/OW}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/UW}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/clk}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/req}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/gnt}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/lrdy}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/add}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/wen}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/data}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/be}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/boffs}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/user}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/r_data}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/r_valid}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/r_opc}
add wave -noupdate -group {tcdm_master[2]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[2]/r_user}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/DW}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/AW}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/BW}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/WW}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/OW}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/UW}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/clk}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/req}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/gnt}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/lrdy}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/add}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/wen}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/data}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/be}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/boffs}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/user}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/r_data}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/r_valid}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/r_opc}
add wave -noupdate -group {tcdm_master[3]} {/tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/tcdm_master[3]/r_user}
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/NB_CTRLS
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/NB_TRANSFERS
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/CTRL_TRANS_QUEUE_DEPTH
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/GLOBAL_TRANS_QUEUE_DEPTH
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/TWD_QUEUE_DEPTH
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/TCDM_ADD_WIDTH
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/EXT_ADD_WIDTH
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/NB_OUTSND_TRANS
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/MCHAN_BURST_LENGTH
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/AXI_ADDR_WIDTH
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/AXI_DATA_WIDTH
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/AXI_USER_WIDTH
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/AXI_ID_WIDTH
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/AXI_STRB_WIDTH
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/PE_ID_WIDTH
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/TRANS_SID_WIDTH
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/TCDM_OPC_WIDTH
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/EXT_OPC_WIDTH
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/MCHAN_LEN_WIDTH
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/EXT_TID_WIDTH
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/clk_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/rst_ni
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/test_mode_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/ctrl_targ_req_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/ctrl_targ_type_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/ctrl_targ_be_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/ctrl_targ_add_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/ctrl_targ_data_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/ctrl_targ_id_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/ctrl_targ_gnt_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/ctrl_targ_r_valid_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/ctrl_targ_r_data_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/ctrl_targ_r_opc_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/ctrl_targ_r_id_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/tcdm_init_req_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/tcdm_init_add_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/tcdm_init_type_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/tcdm_init_be_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/tcdm_init_data_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/tcdm_init_sid_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/tcdm_init_gnt_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/tcdm_init_r_valid_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/tcdm_init_r_data_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_aw_valid_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_aw_addr_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_aw_prot_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_aw_region_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_aw_len_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_aw_size_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_aw_burst_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_aw_lock_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_aw_cache_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_aw_qos_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_aw_id_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_aw_user_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_aw_ready_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_ar_valid_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_ar_addr_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_ar_prot_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_ar_region_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_ar_len_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_ar_size_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_ar_burst_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_ar_lock_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_ar_cache_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_ar_qos_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_ar_id_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_ar_user_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_ar_ready_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_w_valid_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_w_data_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_w_strb_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_w_user_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_w_last_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_w_ready_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_r_valid_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_r_data_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_r_resp_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_r_last_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_r_id_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_r_user_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_r_ready_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_b_valid_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_b_resp_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_b_id_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_b_user_i
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/axi_master_b_ready_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/term_evt_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/term_int_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/busy_o
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_clk_gated
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tcdm_tx_req
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tcdm_rx_req
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_ext_tx_req
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_ext_rx_req
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tcdm_tx_gnt
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tcdm_rx_gnt
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_ext_tx_gnt
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_ext_rx_gnt
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_ext_tx_bst
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_ext_rx_bst
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tcdm_tx_len
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tcdm_rx_len
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_ext_tx_len
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_ext_rx_len
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tcdm_tx_opc
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tcdm_rx_opc
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_ext_tx_opc
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_ext_rx_opc
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tcdm_tx_add
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tcdm_rx_add
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_ext_tx_add
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_ext_rx_add
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_ext_rx_tcdm_add
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tcdm_tx_sid
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tcdm_rx_sid
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_ext_tx_sid
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_ext_rx_sid
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tx_data_push_req
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tx_data_push_gnt
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_rx_data_pop_req
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_rx_data_pop_gnt
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tx_data_push_dat
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_rx_data_pop_dat
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_rx_data_push_gnt
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tx_data_pop_req
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_rx_data_push_req
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tx_data_pop_gnt
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tx_data_pop_strb
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_rx_data_pop_strb
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_rx_data_push_dat
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tx_data_pop_dat
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_trans_tx_ext_add
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_trans_rx_ext_add
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_trans_tx_tcdm_add
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_trans_rx_tcdm_add
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_trans_tx_len
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_trans_rx_len
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_trans_tx_req
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_trans_rx_req
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_trans_tx_gnt
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_trans_rx_gnt
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tx_tcdm_synch_req
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_rx_tcdm_synch_req
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tx_ext_synch_req
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_rx_ext_synch_req
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tx_tcdm_synch_sid
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_rx_tcdm_synch_sid
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_tx_ext_synch_sid
add wave -noupdate -group mchan_i /tb_pulp/i_dut/cluster_domain_i/cluster_i/dmac_wrap_i/mchan_i/s_rx_ext_synch_sid
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {14043517441 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 284
configure wave -valuecolwidth 398
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {14043054085 ps} {14043118864 ps}
